#ifndef VERSION_H_
#define VERSION_H_

#define VERSION "à 0.2"

#define CONTRIBUTORS {"Joe Cosentino",            \
                      "Mark Olensen",             \
                      "Gregg Jennings",           \
                      "Louis P. Santill n",       \
                      "Aitor Santamaria Merino",  \
                      "Xavier Florian"}
                       
#define AMOFCONTRIBUTORS    6
#define LONGESTCONTRIBUTOR 23

#define WEBSITE "http://exsoft.webprovider.com/freedos/defrag"
#define EGROUP  "http://www.e-groups.com/group/free-defrag"

/* Defrag help file */
#define HELPFILE "defrag.hlp"

#endif 
