#
# Makefile for files in this directory.
#

compiler = tcc -c
options  = -O -d -Z -w -ml

libman = tlib

all: mouse.lib
        @echo Mouse routines compiled.

mouse.lib: mouse.obj himouse.obj
        @..\..\..\bin\delete mouse.lib
        @$(libman) mouse.lib + mouse.obj
        @$(libman) mouse.lib + himouse.obj
        @..\..\..\bin\delete mouse.bak

mouse.obj: mouse.asm 
        @nasm mouse.asm -f obj -o mouse.obj

himouse.obj: himouse.c mouse.h ..\..\misc\bool.h
        @$(compiler) $(options) himouse.c

clean:
        @..\..\..\bin\delete mouse.obj 
        @..\..\..\bin\delete himouse.obj
        @..\..\..\bin\delete mouse.lib
        @..\..\..\bin\delete *.bak
