#
# Makefile for files in this directory.
#

compiler = tcc -c
options  = -w -d -O -Z -ml

libman   = tlib

all: ovlimpl.lib
     @echo host implementation compiled.

ovlimpl.lib: ovlimpl.obj
     @..\..\..\bin\delete ovlimpl.lib
     @$(libman) ovlimpl.lib + ovlimpl.obj
     @..\..\..\bin\delete ovlimpl.bak

ovlimpl.obj: ovlimpl.c ..\..\modlgate\expected.h \
             ..\main\chkargs.h
     @$(compiler) $(options) -I..\..\misc;..\..\engine\header ovlimpl.c

clean: 
     @..\..\..\bin\delete ovlimpl.obj
     @..\..\..\bin\delete ovlimpl.lib
