#
# Makefile for command line interface.
#

all: cmdefint.lib
     @echo Command line interface compiled.

cmdefint.lib: libs
     @..\..\bin\delete cmdefint.lib
     @..\..\bin\delete cmdefint.bak
     @tlib cmdefint.lib+main\main.lib
     @tlib cmdefint.lib+ovlhost\ovlimpl.lib
     @..\..\bin\delete cmdefint.bak

libs:
     @cd main
     @make
     @cd ..
     @cd ovlhost
     @make
     @cd ..

clean:
     @cd main
     @make clean
     @cd ..
     @cd ovlhost
     @make clean
     @cd ..
     @..\..\bin\delete cmdefint.bak
     @..\..\bin\delete cmdefint.lib
