#
# Makefile for files in this directory.
#

compiler = tcc -c
options  = -O -d -Z -w -ml

libman = tlib

all: main.lib
        @echo Main routines compiled.

main.lib: cmdefint.obj chkargs.obj 
        @..\..\..\bin\delete main.lib
        @$(libman) main.lib + cmdefint.obj
        @$(libman) main.lib + chkargs.obj
        @$(libman) main.lib + checkos.obj
        @..\..\..\bin\delete main.bak

cmdefint.obj: cmdefint.c ..\..\modlgate\modlgate.h ..\..\misc\version.h \
            ..\..\misc\misc.h chkargs.h
        @$(compiler) $(options) -I..\..\misc;..\..\engine\header cmdefint.c

chkargs.obj: chkargs.c ..\..\modlgate\defrpars.h ..\..\misc\bool.h \
             chkargs.h
        @$(compiler) $(options) chkargs.c 

clean:
        @..\..\..\bin\delete chkargs.obj
        @..\..\..\bin\delete cmdefint.obj
        @..\..\..\bin\delete main.lib
