#
# Makefile for information module (fat 12).
#

compiler = tcc -c
libman   = tlib

options = -w -d -Z -O -ml 

incdir = ..\..\engine\header;..\..\modlgate;..\..\misc

all: ..\modbins\infofat.lib
        @echo Information module created.

..\modbins\infofat.lib: infofat.obj flldrvmp.obj defrfact.obj mrkunmve.obj 
        @..\..\..\bin\delete ..\modbins\infofat.lib
        @..\..\..\bin\delete ..\modbins\infofat.bak
        @$(libman) ..\modbins\infofat.lib + infofat.obj
        @$(libman) ..\modbins\infofat.lib + flldrvmp.obj
        @$(libman) ..\modbins\infofat.lib + defrfact.obj
        @$(libman) ..\modbins\infofat.lib + mrkunmve.obj
        @..\..\..\bin\delete ..\modbins\infofat.bak

infofat.obj: infofat.c ..\..\engine\header\fte.h
        @$(compiler) $(options) -I$(incdir) infofat.c

flldrvmp.obj: flldrvmp.c ..\..\modlgate\expected.h ..\..\engine\header\fte.h
        @$(compiler) $(options) -I$(incdir) flldrvmp.c

defrfact.obj: defrfact.c ..\..\engine\header\fte.h ..\..\misc\bool.h \
              infofat.h
        @$(compiler) $(options) -I$(incdir) defrfact.c

mrkunmve.obj: mrkunmve.c ..\..\engine\header\fte.h ..\..\misc\bool.h \
              infofat.h
        @$(compiler) $(options) -I$(incdir) mrkunmve.c

clean:
      @..\..\..\bin\delete infofat.obj
      @..\..\..\bin\delete flldrvmp.obj
      @..\..\..\bin\delete defrfact.obj
      @..\..\..\bin\delete mrkunmve.obj
      @..\..\..\bin\delete walktree.obj
      @..\..\..\bin\delete ..\modbins\infofat.lib

