#
#  Makefile for files in this directory.
#

compiler = tcc -c
options  = -O -d -Z -w

linker   = tcc

all: mkhelp.exe 
   @echo Helpkit build.

mkhelp.exe:  mkhelp.obj checksum.obj helpfile.obj 
   @$(linker) mkhelp.obj checksum.obj helpfile.obj 

mkhelp.obj: mkhelp.c mkhelp.h
   @$(compiler) $(options) mkhelp.c

checksum.obj: checksum.c checksum.h
   @$(compiler) $(options) -DCALCULATION_PROG checksum.c

helpfile.obj: helpfile.c mkhelp.h checksum.h
   @$(compiler) $(options) helpfile.c

clean:
   @..\..\..\bin\delete mkhelp.obj
   @..\..\..\bin\delete checksum.obj
   @..\..\..\bin\delete helpfile.obj
   @..\..\..\bin\delete mkhelp.exe
