#
# Makefile for files in this directory
#

helppages   = index.0
helpkit = ..\helpkit\mkhelp.exe

all: defrag.hlp

defrag.hlp: $(helppages) $(helpkit) defrag.lst
        @$(helpkit) defrag.lst defrag.hlp
        @copy defrag.hlp ..\..\..\bin
        @copy defrag.hlp ..\..
        
clean:
        @..\..\..\bin\delete defrag.hlp        
